Reintroduced changes mistakenly reverted in an old revision of the 'iris' script.

diff --git a/scripts/iris b/scripts/iris
--- a/scripts/iris
+++ b/scripts/iris
@@ -13,12 +13,12 @@ SVCPIDFILE=$LOGDIR/service.%%.pid
 INSTALL_LOG=$LOGDIR/install.log
 DEFAULT_HOSTNAME=0.0.0.0
 WHOAMI=`whoami`
-HEADING_COLOR=2
 
 IRIS_USAGE='iris [options] <command> [<arguments>]
     
 Available commands:
     check       Ensure that Iris is ready to go
+    env         Get/Set the environment
     examples    Install example data
     help        This command
     install     Install dependencies required by Iris
@@ -42,35 +42,41 @@ function _error {
     echo $@
 }
 
-declare -a _json_cache=[]
 function _json_flatten {
-    jsonfile=$1
-    key=$2
-    fields=$3
-    perl -MJSON -e "
-        my \$d = decode_json(join '',<STDIN>)->{$key};
-        print
-            join(\"\n\",
-                map {
-                    my \$j=\$_; join(\"\t\",
-                        map { \$j->{\$_} } qw/$fields/
-                    )
-                } @\$d), \"\n\"
-    " < $jsonfile
+    local jsonfile=$1
+    local key=$2
+    local fields=$3
+    cat $jsonfile | node -e '
+        var p = process;
+        var f = p.argv[2].split(" ");
+        p.stdin.resume();
+        p.stdin.on("data", function (j) { 
+            var o = JSON.parse(j);
+            o[p.argv[1]].forEach(function (e) {
+                console.log(f.map(function (l) { return e[l]; }).join(" "));
+            });
+        });
+    ' $key "$fields"
 }
 
 function _json_lookup {
-    jsonfile=$1
-    fields=$2
-    perl -MJSON -e "
-         my \$d = decode_json(join '',<STDIN>);
-         for (qw/$fields/) { \$d = \$d->{\$_} };
-         print \"\$d\n\";
-    " < $jsonfile
+    local jsonfile=$1
+    local fields=$2
+    cat $jsonfile | node -e '
+        var f = process.argv[1].split(" ");
+        process.stdin.resume();
+        process.stdin.on("data", function (j) {
+            var o = JSON.parse(j);
+            for (i in f) {
+                o = o[f[i]];
+            }
+            console.log(o);
+        });
+    ' "$fields"
 }
 
 function _running_pid {
-    pidfile=$1
+    local pidfile=$1
     if [ -e "$pidfile" ]; then
         xargs ps u -p < $pidfile | awk '!/PID/ {print $2}'
     fi
@@ -88,7 +94,7 @@ function _svc_pidfile {
 function _start_services {
     local svc=$1
     if [ ! -e "$SVC_CONF" ]; then
-        echo "Service configuration [$SVC_CONF] cannot be found!"
+        echo "Service configuration [$SVC_CONF] cannot be found!" 2> /dev/stderr
         iris_cmd_help
         exit 1
     fi
@@ -128,7 +134,7 @@ function _start_services {
 }
 
 function _start_all_iris {
-    pid=`_iris_pid`
+    local pid=`_iris_pid`
     if [ -n "$pid" ]; then
         echo "Iris is already running (pid `cat $PIDFILE`)"
     else
@@ -203,7 +209,7 @@ _help_start="iris start [<service>]
 Starts Iris services. With no arguments, starts all services.
     <service>   Start a specific service"
 function iris_cmd_start {
-    svc=$1
+    local svc=$1
     if [ -n "$svc" ]; then
         if [ -z "`iris_cmd_services $svc`" ]; then
             echo "Service $svc is not a valid service!"
@@ -230,7 +236,7 @@ _help_stop="iris stop [<service>]
 Stops Iris services. With no arguments, stops all of Iris.
     <service>   Stop a specific service"
 function iris_cmd_stop {
-    svc=$1
+    local svc=$1
     if [ -n "$svc" ]; then
         if [ -z "`iris_cmd_services $svc`" ]; then
             echo "Service $svc is not a valid service!"
@@ -293,7 +299,7 @@ function iris_cmd_install {
         shift
     done
 
-    component=$1
+    local component=$1
     if [ -n "$component" ]; then
         if [ "$component" != 'snapdragon' -a \
              "$component" != 'jquery' -a \
@@ -314,7 +320,7 @@ LOG_HEADER
     # Fetch git-managed modules
     
     [ "$verbose" -eq 1 ] && echo "Installing Git modules..."
-    git submodule update --init 2>&1 >> $INSTALL_LOG
+    git submodule update --recursive --init 2>&1 >> $INSTALL_LOG
 
     if [ "$component" == "all" -o "$component" == "node" ]; then
         [ "$verbose" -eq 1 ] && echo "Installing Node modules..."
@@ -345,7 +351,7 @@ LOG_HEADER
 }
 
 # ---------------------------------------------------------------------------
-# IRIS INSTALL
+# IRIS HELP
 # ---------------------------------------------------------------------------
 _help_help="iris help [<command>]
 
@@ -354,7 +360,7 @@ command.
 
     <command>   Specific command to get help for"
 function iris_cmd_help {
-    cmd=$1
+    local cmd=$1
     if [ -n "$cmd" ]; then
         if [ -z "$(declare -f iris_cmd_$cmd)" ]; then
             echo "There's no command called '$cmd'"
@@ -373,6 +379,44 @@ HELP
     cat <<HELP
 $IRIS_USAGE
 HELP
+}
+
+# ---------------------------------------------------------------------------
+# IRIS ENV
+# ---------------------------------------------------------------------------
+_help_env="iris env [<environment>]
+
+Get or set the Iris environment. The environment indicates whether Iris is used 
+in production or development mode. With no argument, just lists the current 
+environment. With an argument, sets that environment and any associated parameters.
+
+<environment> can be:
+
+    dev         Use a development environment
+    prod        Use a production environment"
+function iris_cmd_env {
+    local env=$1
+    if [ -n "$env" ]; then
+        cd $IRIS_HOME/root/js
+        case $env in
+            dev)
+                rm -f iris.js
+                ln -s iris-dev.js iris.js
+                ;;
+            prod)
+                rm -f iris.js
+                echo "Compressing core Javascript..."
+                echo "[FIXME: Not doing anything yet]"
+                ;;
+            *)
+                echo "The environment '$env' is not supported"
+                exit 1
+                ;;
+        esac
+        echo "Set the environment to '$env'"
+    else
+        echo "The current environment is"
+    fi
 }
 
 # ---------------------------------------------------------------------------
@@ -412,7 +456,7 @@ Shows the status of running services.
     
 See also: 'iris services'"
 function iris_cmd_status {
-    svc=$1
+    local svc=$1
     if [ -n "$svc" ]; then
         local service=`iris_cmd_services $svc`
         if [ -z "$service" ]; then
@@ -455,7 +499,11 @@ Lists available service currently configured with Iris (not *running* services).
 See also: 'iris status'"
 function iris_cmd_services {
     local name=$1
-    local hostname=$(_json_lookup $SVC_CONF "settings hostname")
+    if [ ! -e "$SVC_CONF" ]; then
+        echo "File $SVC_CONF does not exist!" > /dev/stderr
+        exit 1
+    fi
+    local hostname=$(_json_lookup $SVC_CONF 'settings hostname')
     [ -z "$hostname" ] && hostname=$DEFAULT_HOSTNAME
     local services
     if [ -n "$name" ]; then
@@ -541,13 +589,15 @@ argument, runs all component checks.
 The following modules are supported:
 
     unit        Only run the Iris unit tests
-    files       Only check file structure"
+    files       Only check file structure
+    integration Only run Iris integration tests"
 function iris_cmd_check {
     local component=$1
     
     if [ -n "$component" ]; then
         if [ "$component" != "unit" -a \
-             "$component" != "files" ]; then
+             "$component" != "files" -a \
+             "$component" != "integration" ]; then
              _error "'$component' is not a valid check component"
              iris_cmd_help check
          fi
@@ -604,12 +654,14 @@ function iris_cmd_check {
         fi
     fi
     
-    if [ "$component" == "all" -o "$component" == "unit" ]; then
+    if [ "$component" == "all" -o \
+         "$component" == "unit" -o \
+         "$component" == "integration" ]; then
     
         # NODEUNIT
         export NODE_PATH=$NODEDIR/node_modules
         cd $IRIS_HOME/test/
-        ./testjs
+        ./testjs $@
     fi
 }
 
